#!/bin/csh -f
#-------------------------------------------------------------------------------
#-- Title      : script to compile sources for system-simulation
#-- Project    : 



echo " SIMULATE RedFir Filter"


set rtl_path     = ../../../src/vhd
set tb_path      = $rtl_path/tb
set coregen_path = ../../../src/coregen

set worklib  = ./work



vlib work
vmap work work


# filter sources 
# ----------------------------------------------------------------

vcom -93 -work  work $rtl_path/modules_default.vhd
vcom -93 -work  work $rtl_path/example.vhd


# filter testbench
# ---------------------------------------------------------------

vcom -93 -work work $tb_path/FIR_tb.vhd
